theme: jekyll-theme-minimal
title: mercurial tutor co.
description: Brandon Mazey | MS Computer Science NYU Tandon School of Engineering
logo: /images/headshot.jpg
background-image: /images/watercolor.jpg
show_downloads: false