theme: jekyll-theme-minimal
title: mercurial tutor co.
description: Brandon J. Mazey | github.com/mercurial-tutor | mercurial.tutor@gmail.com | +1.929.483.2996
logo: /images/headshot.jpg
show_downloads: false